### ISSUE TITLE
Post code doesn't provide the correct mapping - any other means of location ?

### ISSUE THREAD

**Issue by Salsa4water-Lyon** [4water/weare4water.org#11]
Hi,
Entering the exact post code of the town wherer we give salsa classes provides a very approximate location (some 40 minutes on feet from our real place). Is it possible to use any other means to get the correst location (e.g. eath coordinates) ?

**Comment by iporter** [comment]
Hi, I've updated the field label to 'Address' and modified the code such that it now works.  Please update the field with a more specific address - anything that works on maps.google.com should work here.

Cheers.
