### ISSUE TITLE
Abundant spam comments - any means to prevent other than one-by-one sorting ?

### ISSUE THREAD

**Issue by Salsa4water-Lyon** [4water/weare4water.org#12]
We have only two posts on our news page (both dating from the last year), and recently we had something like one hundred spam comments on them in one week. Is it possible to apply any filter or privacy policy in order to prevent it ?

**Comment by iporter** [comment]
Has this improved?  I installed additional anti-spam measures.

**Comment by iporter** [comment]
I've had a look and found very few spam comments in any site other than Edinburgh.  Edinburgh built up roughly 2000 comments between May and July, but none since, which is presumably when I implemented the fix.  I'll close this issue until further notice.
