### ISSUE TITLE
Different menu tabs for each salsa city homepage

### ISSUE THREAD

**Issue by Salsa4water-Lyon** [4water/weare4water.org#13]
When going to the home pages of each city in the salsa section, the menu tabs are different from city to city. When I started to work on the website, I was talled there were going to be the same tabs for each city. Do we still apply this coherency policy or does each city chose by itself what suites it better ?
Some examples of salsa cities' menues :
Salsa in Prague :
![image](https://cloud.githubusercontent.com/assets/7727658/3112054/727118c8-e6ba-11e3-99c5-440aa31d4916.png)
Salsa in Glasgow :
![image](https://cloud.githubusercontent.com/assets/7727658/3112057/77e7bb22-e6ba-11e3-8fcb-2f036bd9b421.png)
Salsa in CPH :
![image](https://cloud.githubusercontent.com/assets/7727658/3112059/7e17dafe-e6ba-11e3-8983-cd84c2e5321f.png)

**Comment by samson4water** [comment]
Hi 

This can be tailored by yourself. The titles of pages are being played with by myself and Tanmay, to see what is most easy to use and what is best for SEO whilst keeping the website functional and usable.

Eventually we will decide on a way that is best and convert everyone to that way. In the meantime, feel free to change the menu titles to suit. Following Salsa4water Glasgow is likely to be the most effective way as we are playing around with SEO

Let me know if you have problems changing the page titles.

Thanks again for the feedback
Sam
