### ISSUE TITLE
Design : green labels on slides

### ISSUE THREAD

**Issue by Salsa4water-Lyon** [4water/weare4water.org#14]
It can be a question of personal taste (like the fonts choice) but I was unable to get why the labels on slides were green. The colours of all the 4water movement are black+white+blue and some red, so I do perceive the green labels as not quite harmonious. Sorry for being so difficult :)
Screenshot :
![image](https://cloud.githubusercontent.com/assets/7727658/3112125/88f11b24-e6bb-11e3-966c-7d829d2ccfa1.png)

**Comment by samson4water** [comment]
Hi there

Thank you for your feedback. I see the logic behind this feedback but changing the colours for the website would quite a big change, and the colours were picked in combination so changing the green colour means changing the purple etc. Additionally, these colours were picked to demonstrate fun and charity, and were approved by quite a few people before it developed. 

Thank you very much for this opinion I do see where you are coming from :)
All the best
Sam
