### ISSUE TITLE
Issues with the Main page Header

### ISSUE THREAD

**Issue by weare4water** [4water/weare4water.org#2]
In the main header menu page, the excess height of the menu needs to be removed- too much empty blue space. Menu items can be brought inline with the 4water logo. The reason is that the first thing you see on the website looks nice, but you have to scroll down to get any information. Ideally, the amount of money raised would be visible on this page, which might be made possible by reducing the height of the blue menu bar.

Remove facebook link- it's not the most important piece of information and it just uses up space.

I will also change the stuff written in the mission to make it more key-word friendly and add some links

![image](https://cloud.githubusercontent.com/assets/7319423/2838451/efeecbf8-d033-11e3-96d4-d2ed5d401315.png)

**Comment by iporter** [comment]
There was originally an advert for charity bands at the top right - have we decided not to order and promote these?

**Comment by samson4water** [comment]
Hi Iain

We would like to sell the bands, but maybe on the shop, or to have the bands show up on the sidebar?

Also, the bands still show up on the iPhone version.

Thanks
Sam

**Comment by iporter** [comment]
I've removed the bands advert and the Facebook call to action, and shortened the header.
