### ISSUE TITLE
Donate header

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#21]
Don't know if this was mentioned earlier, but this is cluttered and overlapping and just looks unprofessional.
![capture decran 2014-05-30 a 22 27 34](https://cloud.githubusercontent.com/assets/7750063/3135823/0073a512-e839-11e3-8e3b-9642fba9edda.png)

**Comment by iporter** [comment]
Advert and CTA removed.  '4water menu' changed to smaller icon in development environment - will be deployed in due course.
