### ISSUE TITLE
Page bottom

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#22]
4water is unnecessarily large, and frankly this whole bottom of the page thing seems to be pretty large in general. Way to make it more compact so that we can still see some of the better content above it?

![capture decran 2014-05-30 a 22 30 20](https://cloud.githubusercontent.com/assets/7750063/3135874/b240a2b8-e839-11e3-81d9-8b305fa0f328.png)

**Comment by iporter** [comment]
You can upload a smaller image.

**Comment by awmohr** [comment]
Solid, would that affect the site as a whole or simply the relevant city group? (I know that the Prague people can access and edit their stuff but I don't know if we can affect the site as a whole)

**Comment by iporter** [comment]
A change to the footer will affect the whole site. 

The header and footer constant across the whole site are managed via the control panel for the top-level 4water website.  Most content editors will only have access to edit a city and/or project website, so would have to feed a change request through to an editor that did have edit permissions for the top-level website.

Hope that makes sense.
