### ISSUE TITLE
Video Page "Tags"

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#24]
I know some stuff has already been said about the video page and it's organization, but the "Tags" section is just ugly and adds clutter and I don't see its utility. I'd just toss the thing. 

![capture decran 2014-05-30 a 22 39 03](https://cloud.githubusercontent.com/assets/7750063/3135921/7ca019a8-e83a-11e3-8abc-2f2527ffa003.png)

**Comment by iporter** [comment]
Tags are useful from an SEO perspective and, as the video library grows, a usability perspective.
