### ISSUE TITLE
Cities navigation

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#28]
You select a city, then it goes to this page. This should not be here at all it adds an extra step and is weird.

![capture decran 2014-05-30 a 22 55 14](https://cloud.githubusercontent.com/assets/7750063/3136058/c7692720-e83c-11e3-85aa-e368274166d0.png)

**Comment by iporter** [comment]
This page is useful for other cities both for users and SEO.  It may be better to leave the page in for consistency,  but it's up to you if you want to modify the menu to link directly to the salsa linkoping page.
