### ISSUE TITLE
Featured photo

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#29]
This hasn't worked on the Prague page either, it's always just an ugly blank box. 

![capture decran 2014-05-30 a 22 57 05](https://cloud.githubusercontent.com/assets/7750063/3136083/24a6822a-e83d-11e3-912f-5f71cc4957d0.png)

**Comment by iporter** [comment]
This is a map that was broken: see here if you're still having problems: https://github.com/4water/weare4water.org/issues/11
