### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by awmohr** [4water/weare4water.org#30]
The sizing on a lot of headers around the site needs to be reconsidered. Here's an example from our Prague page. This takes up waaaay too much room. I've seen a bunch of other instances of this elsewhere.

![capture decran 2014-05-30 a 23 01 19](https://cloud.githubusercontent.com/assets/7750063/3136130/b524369e-e83d-11e3-8da3-22b9516e3c29.png)

**Comment by iporter** [comment]
I've reduced the line-height where ever this font is used.
