### ISSUE TITLE
Update Map and way the cities display on it

### ISSUE THREAD

**Issue by samson4water** [4water/weare4water.org#32]
1) Change the current map to Myrias map (jpeg without the city names will be posted below by Myria)

![image](https://cloud.githubusercontent.com/assets/7747932/3139742/2e92fe8e-e8ed-11e3-9749-220b41e55c14.png)

2) Change the labels to be round/small red dots, as having the big labels doesn't work, and will get even worse as we expand. When hovering over the red dot with the cursor, then maybe the city name/project can come up. Other options from red dots would be fine, but either way, the labels need to be smaller.

Thanks
Sam

**Comment by myria4water** [comment]
hi,

here is the better version of the map
![sie_4water_map_01](https://cloud.githubusercontent.com/assets/7758062/3140709/421e77e2-e935-11e3-860c-bf2b2a6195e3.png)

and 

![sie_4water](https://cloud.githubusercontent.com/assets/7758062/3140710/4c8ca3c0-e935-11e3-95da-61581c858230.jpg)

**Comment by iporter** [comment]
Complete
